@startuml
!define RECTANGLE class

skinparam linetype ortho

RECTANGLE "Собственники" as Собственники <<Пользователи>> {
}

RECTANGLE "Жильцы" as Жильцы <<Пользователи>> {
}

RECTANGLE "Партнерская платформа\n"Умный дом"" as ПартнерскаяПлатформа <<Внешняя система>> {
}


RECTANGLE "PropDevelopment" as PropDevelopment <<Система>> {
}

Собственники --> PropDevelopment : Использует мобильное приложение\nдля управления сервисами
Жильцы --> PropDevelopment : Использует домофон/шлагбаум
PropDevelopment --> ПартнерскаяПлатформа : Интеграция через API\n(управление домофоном и шлагбаумом)


@enduml